version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver_loc:
        #image: puckel/docker-airflow:1.8.0
        build:
            dockerfile: Dockerfile
            context: .
        container_name: airflow-local
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        volumes:
            - ${AIRFLOW_DAGS}:/usr/local/airflow/dags
            - ${LOVE_MATCHER_PROJECT}:/usr/local/love_matcher_project
        ports:
            - "8078:8080"
        command: webserver
