version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: toinouf/airflow:testing
        #build:
        #    dockerfile: Dockerfile
        #    context: .
        container_name: airflow-celery
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ${LOVE_MATCHER_PROJECT}/love_matcher_exercises/dags:/usr/local/airflow/dags
            - ${LOVE_MATCHER_PROJECT}:/usr/local/love_matcher_project
        ports:
            - "8077:8080"
        command: webserver

    flower:
        image: toinouf/airflow:testing
        #build:
        #    dockerfile: Dockerfile
        #    context: .
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: toinouf/airflow:testing
        #build:
        #    dockerfile: Dockerfile
        #    context: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ${LOVE_MATCHER_PROJECT}/love_matcher_exercises/dags:/usr/local/airflow/dags
            - ${LOVE_MATCHER_PROJECT}:/usr/local/love_matcher_project
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: scheduler

    worker:
        image: toinouf/airflow:testing
        #build:
        #    dockerfile: Dockerfile
        #    context: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ${LOVE_MATCHER_PROJECT}/love_matcher_exercises/dags:/usr/local/airflow/dags
            - ${LOVE_MATCHER_PROJECT}:/usr/local/love_matcher_project
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: worker
